### PR TITLE
Additional documentation on Docker setup for RDKit + Jupyter integration

### PR DESCRIPTION
**Pull request by simonkeng**
Hi @greglandrum, 

I've noticed that some of the installation instructions in `rdkit/rdkit_containers/docker/run_conda3/README` might be a little out of date, as I have had some level of difficulty getting everything working. My coworker and I recently collaborated on [this repository](https://github.com/simonkeng/rdkit-jupyter-docker), hoping to provide an "out of the box" build for any newcomers. In my experience, getting RDKit's dependancies synchronized with Conda and Jupyter is not very straight forward, especially for newcomers unfamiliar with these tools. Let me know what you think, and thank you for your time. 

Sincerely, 

Simon Keng

### CODE REVIEW

**Comment by simonkeng** [comment]
Hi @greglandrum, I was just curious if you had a chance to read this pull request. Thanks, and it was great meeting you during your visit to Portland.

**Comment by greglandrum** [comment]
Hi @simonkeng, thanks for the ping.
Given how much superior the documentation you've done is than what's here I would prefer to do one of two things:
1) Move the suggested changes you've made to the very top of this file so that people see the pointer to the better documented setup first.
2) Merge all the changes in your repo into this one

I'm happy to go either way with it.

**Comment by simonkeng** [comment]
Hi @greglandrum, 

This is fantastic news! I went ahead with option 2 and created a new [pull request](https://github.com/rdkit/rdkit_containers/pull/2) containing all the changes in my repo. Let me know if there is anything else I can do. 

Thanks for giving me an opportunity to contribute! 

Simon

**Comment by greglandrum** [comment]
I think it’s safe to close this now, right?

**Comment by simonkeng** [comment]
Yes absolutely, thanks again @greglandrum

**Pull request closed without merging**
